config/routes.rb
Rails.application.routes.draw do
  resources :phones
  resources :addresses
  resources :connections
  resources :kinds

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :connection
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :kind
end

app/models/kind.rb
class Kind < ActiveRecord::Base
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :connection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # GET /connections
  # GET /connections.json
  def index
    @connections = Connection.all
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render :show, status: :created, location: @connection }
      else
        format.html { render :new }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @connection }
      else
        format.html { render :edit }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url, notice: 'Connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.require(:connection).permit(:name, :email, :kind_id, :remark)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/connections/_form.html.erb
<%= form_for(@connection) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= collection_select(:connection, :kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_area :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing Connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<br>
<div class="basic-grey">
  <script>
    $.notify("<%= notice %>", "success");
  </script>


<h1><%="#{t('messages.listing')} #{@connections.model.model_name.human(count: @connections.count)}"%></h1>

<table>
  <thead>
    <tr>
      <th><%= @connections.model.human_attribute_name("name") %></th>
      <th><%= @connections.model.human_attribute_name("kind_id") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr style="background-color: <%= cycle('white', 'lightgrey') %>">
        <td><%= connection.name %></td>
        <td><%= connection.kind.description %></td>
        <td><%= link_to t('buttons.show'), connection %></td>
        <td><%= link_to t('buttons.edit'), edit_connection_path(connection) %></td>
        <td><%= link_to t('buttons.destroy'), connection, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @connections %>

<br>

<%= link_to t('buttons.new'), new_connection_path, class: "btn btn-primary" %>
<%= link_to t('buttons.home'), root_path, class: "btn btn-success" %>
</div>

app/views/connections/new.html.erb
<h1>New Connection</h1>

<%= render 'form' %>

<%= link_to 'Back', connections_path %>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @connection.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @connection.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @connection.kind %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @connection.remark %>
</p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>

app/views/home/index.html.erb
<h1>Bem vindo!</h1>
<ul>
    <li><%= link_to "Tipos", kinds_path %></li>
    <li><%= link_to "Contatos", connections_path %></li>
    <li><%= link_to "Endereços", addresses_path %></li>
    <li><%= link_to "Telephones", phones_path %></li>
</ul>

app/views/kinds/_form.html.erb
<%= form_for(@kind) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form' %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kinds</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to 'Show', kind %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kind', new_kind_path %>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form' %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>